### ISSUE TITLE
adding cache in either wt or ro mode greatly reduces read performance

### ISSUE THREAD

**Issue by andenix** [stec-inc/EnhanceIO#97]
When I add eio_cli create -d /dev/sda3 -s /dev/sdc -c my_first_enhanceio

  where __sdc__ is my SSD drive and __sda3__ my __/home__

My read speed drops by a factor of 10-15x
I tried removing the cache while copying the file and read speed gets to normal.

Using 4.0.4 kernel on __Debian 64__

EhcnceIO compiled from git.

**Comment by andenix** [comment]
I didn't try wb mode because writ speed of my SSD is low.

**Comment by onlyjob** [comment]
IMHO your problem is because all reads from cached device are also written to caching device. Therefore with cache attached you will not be able to read faster than your SSD can write. As far as I'm aware this is a typical problem with _EnhanceIO_, _flashcache_, _bcache_ and _dm-cache_ (but not with _[dm-writeboost](https://github.com/akiradeveloper/dm-writeboost)_ because the latter is not focused on caching reads).

Besides on [Debian](http://debian.org) it might be better (and easier) to use [official package](https://packages.qa.debian.org/e/enhanceio.html).

**Comment by andenix** [comment]
I never thanked you for the insights and probable ways of resolution. Thank you.

**Comment by onlyjob** [comment]
I'm glad if my information was useful to you. :)
